# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Automatic response evaluation using LLM rubric scoring

# Note: set configs and secrets via environment variables or CI secrets management
# See: https://www.promptfoo.dev/docs/usage/command-line > Environment variables

prompts:
  - file://prompts/prompts.txt

providers:
  # - openai:chat:gpt-4o
  # - anthropic:messages:claude-sonnet-4-20250514
  
  # Custom providers
  - id: litellm:chat:aws/claude-3-7-sonnet
    config:
      apiBaseUrl: https://litellm.sbp.ai
  - id: litellm:chat:azure/gpt-5-mini
    config:
      apiBaseUrl: https://litellm.sbp.ai

defaultTest:
  # By default, llm-rubric assertion uses `gpt-4.1-2025-04-14` for grading,
  # but it can be overridden for all tests or per test.
  options:
    provider:
      id: github:openai/gpt-4.1-nano
  
  assert:
    # - type: llm-rubric
    #   value: Do not mention that you are an AI or chat assistant
    - type: javascript
      # Shorter is better
      value: Math.max(0, Math.min(1, 1 - (output.length - 100) / 900));

tests:
  - vars:
      name: Bob
      question: Can you help me find a specific product on your website?
  - vars:
      name: Jane
      question: Do you have any promotions or discounts currently available?
  - vars:
      name: Ben
      question: Can you check the availability of a product at a specific store location?
  - vars:
      name: Dave
      question: What are your shipping and return policies?
  - vars:
      name: Jim
      question: Can you provide more information about the product specifications or features?
  - vars:
      name: Alice
      question: Can you recommend products that are similar to what I've been looking at?
  - vars:
      name: Sophie
      question: Do you have any recommendations for products that are currently popular or trending?
  - vars:
      name: Jessie
      question: How can I track my order after it has been shipped?
  - vars:
      name: Kim
      question: What payment methods do you accept?
  - vars:
      name: Emily
      question: Can you help me with a problem I'm having with my account or order?
